name: motionenergy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyter
  - notebook
  - ipywidgets
  - scikit-image
  - opencv
  - pillow
  - numba
  - tqdm
  - pip
  - pip:
    - pywavelets
    - celluloid 